apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-01-hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: devops-01-hello
  template:
    metadata:
      labels:
        app: devops-01-hello
    spec:
      containers:
        - name: devops-01-hello
          image: asoner01/devops-01-hello:v001
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9090